/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/index.css': { assetKey: '/index.css', contentType: 'text/css', isText: true, fileInfo: { size: 466, hash: 'e17878bc37ca054789c91f5c24e6044a077e172d2c65454a71269a82e61ee686', lastModifiedTime: 1768985591, assetPath: './styles/index.css' }, lastModifiedTime: 1768985591, type: 'wasm-inline' },
};

export { staticAssetManifest };
