/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/index.css': { assetKey: '/index.css', contentType: 'text/css', isText: true, fileInfo: { size: 469, hash: '33301f457d01b81b22d448a9d7d4731de3da9e7618a7b15dfc6b688677d246f1', lastModifiedTime: 1775648879, assetPath: './styles/index.css' }, lastModifiedTime: 1775648879, type: 'wasm-inline' },
};

export { staticAssetManifest };
