/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/index.html': { assetKey: '/index.html', contentType: 'text/html', isText: true, fileInfo: { size: 1010, hash: 'cae9bcf1c0af05f33b86d27874b7765ed33c52e8ab9ca1c26655db917273ef4d', lastModifiedTime: 1775648879, assetPath: './templates/index.html' }, lastModifiedTime: 1775648879, type: 'wasm-inline' },
};

export { staticAssetManifest };
