// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#include "http_reactor.h"


typedef struct {
  bool is_err;
  union {
    gcore_fastedge_http_client_response_t ok;
    gcore_fastedge_http_client_error_t err;
  } val;
} http_reactor_result_gcore_fastedge_http_client_response_gcore_fastedge_http_client_error_t;

__attribute__((__import_module__("gcore:fastedge/http-client"), __import_name__("send-request")))
void __wasm_import_gcore_fastedge_http_client_send_request(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
__attribute__((__weak__, __export_name__("cabi_post_gcore:fastedge/http-handler#process")))
void __wasm_export_exports_gcore_fastedge_http_handler_process_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 4)))) {
    case 0: {
      break;
    }
    case 1: {
      int32_t ptr = *((int32_t*) (arg0 + 8));
      int32_t len = *((int32_t*) (arg0 + 12));
      for (int32_t i = 0; i < len; i++) {
        int32_t base = ptr + i * 16;
        (void) base;
        if ((*((int32_t*) (base + 4))) > 0) {
          free((void*) (*((int32_t*) (base + 0))));
        }
        if ((*((int32_t*) (base + 12))) > 0) {
          free((void*) (*((int32_t*) (base + 8))));
        }
      }
      if (len > 0) {
        free((void*) (ptr));
      }
      break;
    }
  }
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 16)))) {
    case 0: {
      break;
    }
    case 1: {
      int32_t ptr0 = *((int32_t*) (arg0 + 20));
      int32_t len1 = *((int32_t*) (arg0 + 24));
      for (int32_t i2 = 0; i2 < len1; i2++) {
        int32_t base = ptr0 + i2 * 1;
        (void) base;
      }
      if (len1 > 0) {
        free((void*) (ptr0));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[28];

bool gcore_fastedge_http_client_send_request(gcore_fastedge_http_client_request_t *req, gcore_fastedge_http_client_response_t *ret, gcore_fastedge_http_client_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[32];
  int32_t option;
  int32_t option1;
  int32_t option2;
  if (((*req).body).is_some) {
    const gcore_fastedge_http_body_t *payload0 = &((*req).body).val;
    option = 1;
    option1 = (int32_t) (*payload0).ptr;
    option2 = (int32_t) (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_gcore_fastedge_http_client_send_request((int32_t) (*req).method, (int32_t) ((*req).uri).ptr, (int32_t) ((*req).uri).len, (int32_t) ((*req).headers).ptr, (int32_t) ((*req).headers).len, option, option1, option2, ptr);
  http_reactor_result_gcore_fastedge_http_client_response_gcore_fastedge_http_client_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      http_reactor_option_gcore_fastedge_http_headers_t option3;
      switch ((int32_t) (*((uint8_t*) (ptr + 8)))) {
        case 0: {
          option3.is_some = false;
          break;
        }
        case 1: {
          option3.is_some = true;
          option3.val = (gcore_fastedge_http_headers_t) { (http_reactor_tuple2_string_string_t*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
          break;
        }
      }
      http_reactor_option_gcore_fastedge_http_body_t option4;
      switch ((int32_t) (*((uint8_t*) (ptr + 20)))) {
        case 0: {
          option4.is_some = false;
          break;
        }
        case 1: {
          option4.is_some = true;
          option4.val = (gcore_fastedge_http_body_t) { (uint8_t*)(*((int32_t*) (ptr + 24))), (size_t)(*((int32_t*) (ptr + 28))) };
          break;
        }
      }

      result.val.ok = (gcore_fastedge_http_response_t) {
        (uint16_t) ((int32_t) (*((uint16_t*) (ptr + 4)))),
        option3,
        option4,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

__attribute__((__export_name__("gcore:fastedge/http-handler#process")))
int32_t __wasm_export_exports_gcore_fastedge_http_handler_process(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6) {
  http_reactor_option_gcore_fastedge_http_body_t option;
  switch (arg4) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (gcore_fastedge_http_body_t) { (uint8_t*)(arg5), (size_t)(arg6) };
      break;
    }
  }
  gcore_fastedge_http_handler_request_t arg7 = (gcore_fastedge_http_request_t) {
    arg,
    (http_reactor_string_t) { (char*)(arg0), (size_t)(arg1) },
    (gcore_fastedge_http_headers_t) { (http_reactor_tuple2_string_string_t*)(arg2), (size_t)(arg3) },
    option,
  };
  gcore_fastedge_http_handler_response_t ret;
  exports_gcore_fastedge_http_handler_process(&arg7, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int16_t*)(ptr + 0)) = (int32_t) ((ret).status);
  if (((ret).headers).is_some) {
    const gcore_fastedge_http_headers_t *payload8 = &((ret).headers).val;
    *((int8_t*)(ptr + 4)) = 1;
    *((int32_t*)(ptr + 12)) = (int32_t) (*payload8).len;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload8).ptr;
  } else {
    *((int8_t*)(ptr + 4)) = 0;
  }
  if (((ret).body).is_some) {
    const gcore_fastedge_http_body_t *payload10 = &((ret).body).val;
    *((int8_t*)(ptr + 16)) = 1;
    *((int32_t*)(ptr + 24)) = (int32_t) (*payload10).len;
    *((int32_t*)(ptr + 20)) = (int32_t) (*payload10).ptr;
  } else {
    *((int8_t*)(ptr + 16)) = 0;
  }
  return ptr;
}

extern void __component_type_object_force_link_http_reactor(void);
void __component_type_object_force_link_http_reactor_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_http_reactor();
}
