name: 'Setup Node.js'
description: 'Sets up Node.js environment and installs dependencies.'
inputs:
  node_version:
    description: 'Node.js version to use, e.g. 20.x'
    required: false
    default: '24.12.0'
  pnpm_version:
    description: 'pnpm version to use, e.g. 10.x'
    required: false
    default: '10.x'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm_version }}

    - name: Get pnpm store location
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies (pnpm)
      shell: bash
      run: |
        pnpm install --frozen-lockfile
      # equivalent to npm ci
