/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/assets/index-COcDBgFa.css': { assetKey: '/assets/index-COcDBgFa.css', contentType: 'text/css', isText: true, fileInfo: { size: 1381, hash: '053fffbd3cb2f092a85d67a83459e078b9fe405f2da931b9d21d03d6a853bf34', lastModifiedTime: 1776092001, assetPath: './dist/assets/index-COcDBgFa.css' }, lastModifiedTime: 1776092001, type: 'wasm-inline' },
  '/assets/index-DjqI1cle.js': { assetKey: '/assets/index-DjqI1cle.js', contentType: 'application/javascript', isText: true, fileInfo: { size: 195714, hash: '7b7102e112107e13c808d2d82ce9df83bcb9199808112cd2bbf4b35048e17aaa', lastModifiedTime: 1776092001, assetPath: './dist/assets/index-DjqI1cle.js' }, lastModifiedTime: 1776092001, type: 'wasm-inline' },
  '/assets/react-CHdo91hT.svg': { assetKey: '/assets/react-CHdo91hT.svg', contentType: 'image/svg+xml', isText: true, fileInfo: { size: 4126, hash: '35ef61ed53b323ae94a16a8ec659b3d0af3880698791133f23b084085ab1c2e5', lastModifiedTime: 1776092001, assetPath: './dist/assets/react-CHdo91hT.svg' }, lastModifiedTime: 1776092001, type: 'wasm-inline' },
  '/index.html': { assetKey: '/index.html', contentType: 'text/html', isText: true, fileInfo: { size: 463, hash: '96073e01ae8aa8a822a0c5960219ede99df8839186cc3598da3dad7a46b134ee', lastModifiedTime: 1776092001, assetPath: './dist/index.html' }, lastModifiedTime: 1776092001, type: 'wasm-inline' },
  '/vite.svg': { assetKey: '/vite.svg', contentType: 'image/svg+xml', isText: true, fileInfo: { size: 1497, hash: '4a748afd443918bb16591c834c401dae33e87861ab5dbad0811c3a3b4a9214fb', lastModifiedTime: 1776092001, assetPath: './dist/vite.svg' }, lastModifiedTime: 1776092001, type: 'wasm-inline' },
};

export { staticAssetManifest };
