/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/assets/index-9jaZKl3E.js': { assetKey: '/assets/index-9jaZKl3E.js', contentType: 'application/javascript', isText: true, fileInfo: { size: 193167, hash: '0d24f9f225bc2f2ad59f638fae48474b97b95dbdd9a66780902e8c5d629d6a69', lastModifiedTime: 1782741196, assetPath: './dist/assets/index-9jaZKl3E.js' }, lastModifiedTime: 1782741196, type: 'wasm-inline' },
  '/assets/index-hoDP6v4Q.css': { assetKey: '/assets/index-hoDP6v4Q.css', contentType: 'text/css', isText: true, fileInfo: { size: 1553, hash: '6747fc46412fa77c263e7ad1aef9fc5e5d4a3992a4d61af856701f604da038f9', lastModifiedTime: 1782741196, assetPath: './dist/assets/index-hoDP6v4Q.css' }, lastModifiedTime: 1782741196, type: 'wasm-inline' },
  '/assets/react-CHdo91hT.svg': { assetKey: '/assets/react-CHdo91hT.svg', contentType: 'image/svg+xml', isText: true, fileInfo: { size: 4126, hash: '35ef61ed53b323ae94a16a8ec659b3d0af3880698791133f23b084085ab1c2e5', lastModifiedTime: 1782741196, assetPath: './dist/assets/react-CHdo91hT.svg' }, lastModifiedTime: 1782741196, type: 'wasm-inline' },
  '/index.html': { assetKey: '/index.html', contentType: 'text/html', isText: true, fileInfo: { size: 463, hash: '9d14148f80c294fd76d895bbf4dd239f581c4b76ba1a05783b18d2182cd7584e', lastModifiedTime: 1782741196, assetPath: './dist/index.html' }, lastModifiedTime: 1782741196, type: 'wasm-inline' },
  '/vite.svg': { assetKey: '/vite.svg', contentType: 'image/svg+xml', isText: true, fileInfo: { size: 1497, hash: '4a748afd443918bb16591c834c401dae33e87861ab5dbad0811c3a3b4a9214fb', lastModifiedTime: 1782741196, assetPath: './dist/vite.svg' }, lastModifiedTime: 1782741196, type: 'wasm-inline' },
};

export { staticAssetManifest };
