name: Unit Tests

on:
  push:
    branches: [testing-actions]

  pull_request:
    branches: [npm-packaging]

jobs:
  code_validation:
    uses: ./.github/workflows/code-validation.yml

  unit_tests:
    uses: ./.github/workflows/unit-tests.yml
