name: Pull Request Requirements

on:
  push:
    branches: [testing-actions]
  # pull_request:
  #   branches: [npm-packaging]
  workflow_dispatch: # trigger manually

jobs:
  pr_verify_code:
    uses: ./.github/workflows/code-validation.yaml

  pr_run_unit_tests:
    uses: ./.github/workflows/unit-tests.yaml
